logging:
  level:
    org:
      springframework:
        security: INFO
spring:
  application:
    name: Laelith VTT Application

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true

server:
  port: 8080
security:
  jwt:
    public-key: |
      -----BEGIN PUBLIC KEY-----
      MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAprtbaZyJPSH+0r4K0f41
      WIrdUCWKGVKUHrbVymFacHAFtpOGz30Fx3VmLptVuhQlT76GZ9yuDxEA/azG5/dM
      zEfHTWQmtVZrVijS9V1/8999Wxd/C6jBFZdhPIGEYnWz6i/KgJMsjOcU+bIXUR6R
      jVE/XYCpqN/BY1Fkf4cl1UCuqqoHS1InHUDcyoKH9u/JAz5k7QcJfIrOo+ckxvVl
      fd2DwgYeIKJn7/QunV+4lccSBKcn5mkrpAFNw81SVFTK4Y+FucIR6g6XSsk8CI/s
      MOJXQpHetija0R2dpzmwk1cpPBSRV6ioWsMAIL5YdNG7qcX2nPBj6jWz+sWRMy9B
      ttsO+KHD76q7UnBU4M6//QFYoUXYc2TYgI/Yx5iWKXFCBb2dqtXgLnh256Ojjf52
      MrTY37YjcIlJEPYPOICnMjAN/3xVxYaWLzQ1kJXJNxmPvvREXir/VW55f2tUxdeh
      X42Kv2NddNCWoEwD2Lj8pSxaH6N8epuiN/Tl5R4P6DMtjWVDZRxI26NaCbgZnCjx
      2n8krdoFK+8ZVvUjZHhzulW77Nhp5wg+lrYQhKBoAoahfhk6VKCYqTEDzrRiJ+gS
      07QXWKopazghpxsk6TTpm9uCu1t7mTF5OKHbxevUbSS41krkS7HVCFlnahWgunzU
      BZLJrUyY6EI6wsygAWs7FYMCAwEAAQ==
      -----END PUBLIC KEY-----
