name: Create and publish a Docker image

on:
  release:
    types: [created]

env:
  REGISTRY: ghcr.io
  DO_REGISTRY: registry.digitalocean.com/bitfu
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build Docker image and push ghcr
        run: ./gradlew bootBuildImage
        env:
          CR_IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          CR_TAG: ${{ github.event.release.tag_name }}
          CR_USERNAME: ${{ github.actor }}
          CR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          BUILD_SCAN: true
      - name: Build Docker image and push digital ocean
        run: ./gradlew bootBuildImage
        env:
          CR_IMAGE: ${{ env.DO_REGISTRY }}/${{ env.IMAGE_NAME }}
          CR_TAG: ${{ github.event.release.tag_name }}
          CR_USERNAME: ${{ secrets.DO_TOKEN }}
          CR_PASSWORD: ${{ secrets.DO_TOKEN }}
          BUILD_SCAN: true
