openapi: 3.0.0
info:
  title: Laelith VTT API
  description: Laelith VTT API
  version: 1.0.0
servers:
    - url: http://localhost:8080
      description: Local server
    - url: https://vtt.laelith.com
      description: VTT laelith server
    - url: https://vtt.test.laelith.com
      description: VTT laelith test server
security:
  - oAuth2AuthCode: [ ]
tags:
  - name: base
    description: Base API
  - name: dice
    description: Dice roll API
paths:
  /info:
    get:
      summary: Get server info
      operationId: info
      tags:
        - base
      responses:
        200:
          description: Server info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Info'
  /dice/roll:
    post:
      summary: Roll dice
      operationId: roll
      tags:
        - dice
      requestBody:
        description: Dice roll request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DiceRollRequest'
      responses:
        200:
          description: Dice roll result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DiceRollResults'
  /dice/rolls:
    get:
      summary: Roll dice
      operationId: rolls
      tags:
        - dice
      responses:
        200:
          description: Dice roll result
          content:
            text/event-stream:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DiceRollResults'
  /experience:
    post:
      summary: Add VTT experience
      operationId: addExperience
      tags:
        - experience
      requestBody:
        description: Experience to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExperienceIn'
      responses:
        201:
          description: Experience added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Experience'
    get:
      summary: List of VTT experiences stream
      operationId: listExperience
      tags:
        - experience
      responses:
        200:
          description: VTT experience list
          content:
            text/event-stream:
              schema:
                type: array
                items:
                  type: object
                  additionalProperties:
                    $ref: '#/components/schemas/Experience'
  /experience/{id}:
    parameters:
      - name: id
        in: path
        description: Experience id
        required: true
        schema:
          type: string
    get:
      summary: Get VTT experience
      operationId: getExperience
      tags:
          - experience
      responses:
        200:
          description: Experience
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Experience'
    delete:
      summary: Remove VTT experience
      operationId: removeExperience
      tags:
          - experience
      responses:
        200:
          description: Experience removed
  /experience/{id}/join:
    parameters:
      - name: id
        in: path
        description: Experience id
        required: true
        schema:
          type: string
    get:
      summary: Join VTT experience main stream
      operationId: joinExperience
      tags:
        - experience
      responses:
        200:
          description: VTT experience main stream
  /experience/{id}/quit:
    parameters:
      - name: id
        in: path
        description: Experience id
        required: true
        schema:
          type: string
    post:
      summary: Quit VTT experience stream
      operationId: quitExperience
      tags:
        - experience
      responses:
        201:
          description: VTT experience quit
  /experience/{id}/roll:
    parameters:
      - name: id
        in: path
        description: Experience id
        required: true
        schema:
          type: string
    post:
      summary: Roll dice
      operationId: experienceRoll
      tags:
        - experience
      requestBody:
        description: Dice roll request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DiceRollRequest'
      responses:
        200:
          description: Dice roll OK
  /experience/{id}/events/rolls:
    parameters:
      - name: id
        in: path
        description: Experience id
        required: true
        schema:
          type: string
    get:
      summary: Roll dice
      operationId: experienceEventRolls
      tags:
        - experience
      responses:
        200:
          description: Experience dice roll result
          content:
            text/event-stream:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DiceRollResults'
  /experience/{id}/events/experience:
    parameters:
      - name: id
        in: path
        description: Experience id
        required: true
        schema:
          type: string
    get:
      summary: Experience events
      operationId: experienceEvents
      tags:
        - experience
      responses:
        200:
          description: Experience event
          content:
            text/event-stream:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Experience'

components:
  securitySchemes:
    oAuth2AuthCode:
      type: oauth2
      description: OAuth2 authentication
      flows:
        authorizationCode:
          authorizationUrl: https://id.laelith.com/api/realms/laelith/authorize
          tokenUrl: https://id.laelith.com/api/realms/laelith/token
          refreshUrl: https://id.laelith.com/api/realms/laelith/token
          scopes:
            openid: Open ID
  schemas:
    Info:
      type: object
      properties:
        version:
          type: string
          description: Server version
        name:
          type: string
          description: Application name
        description:
          type: string
          description: Application description
        time:
          type: integer
          format: int64
          description: Server time
    DiceRollRequest:
      type: object
      properties:
        expression:
          type: string
          description: Expression to roll
      required:
        - expression
    DiceRollResults:
      type: object
      description: Result of complex dice roll
      properties:
        expression:
          type: string
          description: Rolled expression
        result:
          type: integer
          description: Result of the roll
        rolls:
          type: array
          items:
            $ref: '#/components/schemas/DiceRollResult'
    DiceRollResult:
      type: object
      description: Result of one dice roll
      properties:
        expression:
          type: string
          description: Rolled expression
        result:
          type: integer
          description: Result of the roll
    ExperienceIn:
      type: object
      description: A VTT experience to add
      properties:
        name:
          type: string
          description: Experience name
    Experience:
      type: object
      description: A VTT experience
      properties:
        id:
          type: string
          description: Experience id
        name:
          type: string
          description: Experience name
        state:
          type: string
          description: Experience state
          enum:
            - created
            - deleted
        users:
          type: array
          description: Experience users
          items:
            type: string
            description: User id
      required:
        - id
        - users
        - state