openapi: 3.0.0
info:
  title: Laelith VTT API
  description: Laelith VTT API
  version: 1.0.0
servers:
    - url: http://localhost:8080
      description: Local server
    - url: https://vtt.laelith.com
      description: VTT laelith server
    - url: https://vtt.test.laelith.com
      description: VTT laelith test server
security:
  - oAuth2AuthCode: [ ]
tags:
  - name: base
    description: Base API
  - name: dice
    description: Dice roll API
paths:
  /info:
    get:
      summary: Get server info
      operationId: info
      tags:
        - base
      responses:
        200:
          description: Server info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Info'
  /dice/roll:
    post:
      summary: Roll dice
      operationId: roll
      tags:
        - dice
      requestBody:
        description: Dice roll request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DiceRollRequest'
      responses:
        200:
          description: Dice roll result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DiceRollResults'
components:
  securitySchemes:
    oAuth2AuthCode:
      type: oauth2
      description: OAuth2 authentication
      flows:
        authorizationCode:
          authorizationUrl: https://id.laelith.com/api/realms/laelith/authorize
          tokenUrl: https://id.laelith.com/api/realms/laelith/token
          refreshUrl: https://id.laelith.com/api/realms/laelith/token
          scopes:
            openid: Open ID
  schemas:
    Info:
      type: object
      properties:
        version:
          type: string
          description: Server version
        name:
          type: string
          description: Application name
        description:
          type: string
          description: Application description
        time:
          type: integer
          format: int64
          description: Server time
    DiceRollRequest:
      type: object
      properties:
        expression:
          type: string
          description: Expression to roll
      required:
        - expression
    DiceRollResults:
      type: object
      description: Result of complex dice roll
      properties:
        expression:
          type: string
          description: Rolled expression
        result:
          type: integer
          description: Result of the roll
        rolls:
          type: array
          items:
            $ref: '#/components/schemas/DiceRollResult'
    DiceRollResult:
      type: object
      description: Result of one dice roll
      properties:
        expression:
          type: string
          description: Rolled expression
        result:
          type: integer
          description: Result of the roll